name: dast owasp zap

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.3.0

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://impacta-juice-shop.herokuapp.com'
          #rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
